### ISSUE TITLE
Settings not retained in Advanced sub application

### ISSUE THREAD

**Issue by captnAmericaa** [transistorsoft/rn-background-geolocation-demo#77] opened 2019-04-01 04:07 UTC
Trying on 

Device : Xiomi Mi A1
Android version : 9.0

I have installed demo App as per instructions. I am trying to use Advanced application out of three provided. Whats happening is whenever I set some settings in Settings menu and press X and come out, after going in settings again , all values gets defaulted. How can I be sure that settings done in first place is retained. Is this is accepted behaviour

**Comment by christocracy** [comment] 2019-04-01 13:48
It's not a bug with the plugin, it's just a UI bug with the app after I updated all the dependencies.

Looking into it.  The settings you *change* are applied correctly to the plugin.  The actual values are simply not rendered correctly to the form-fields.

**Comment by christocracy** [comment] 2019-04-01 13:59
Fixed in master.  I had disabled the state-loading of the form while debugging an issue with updated dependencies.

**Closed** 2019-04-01 13:59 UTC
