### ISSUE TITLE
Android notification drawer

### ISSUE THREAD

**Issue by texas697** [transistorsoft/rn-background-geolocation-demo#26] opened 2016-04-15 10:28 UTC
With the react native demo from the playstore the notification is not available in the notification drawer. This is what I want. When I install my purchased version the notification is available for the user to press. This causes problems. After they press it it returns to the map and it seems to reset the map component. Is this behavior expected or could it be something I have done with my app?

**Comment by christocracy** [comment] 2016-04-15 13:49
The notification is a requirement when configuring foregroundService: true.

configuring foregroundService: true makes the Service far more immune to
being closed by the OS due to memory pressure.

I would expect that pressing the notification should simply focus the app.
This is what happens with the Cordova version.  I suspect the problem is
related to React Native or Android configuration.


On Fri, Apr 15, 2016 at 6:28 AM, Rudy Sanchez <notifications@github.com>
wrote:

> With the react native demo from the playstore the notification is not
> available in the notification drawer. This is what I want. When I install
> my purchased version the notification is available for the user to press.
> This causes problems. After they press it it returns to the map and it
> seems to reset the map component. Is this behavior expected or could it be
> something I have done with my app?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transistorsoft/rn-background-geolocation-demo/issues/26>
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Closed** 2016-06-29 13:26 UTC
